### ISSUE TITLE
Definitions and Acronyms

### ISSUE THREAD

**Issue by anilturkmayali** [International-Data-Spaces-Association/IDS-testbed#10]
Dear all,

Definitions and acronymes that are originated out of Testlab and Testcenter activities should be integrated in the IDS Glossary and Definitions. For this reason, may I kindly ask a list of definitions and acronyms that are provided in the IDS-testbed project? 

Thank you,
Best regards,
Anil

**Comment by jfernandezsqs** [comment]
Hello @anilturkmayali!
I close this issue as there is no feedback of possible acronyms or definitions of this IDS-testbed.
In case in the future there are any, they will be integrated into the IDS Glossary.
