### ISSUE TITLE
Point to point communication - error 

### ISSUE THREAD

**Issue by maliks3** [International-Data-Spaces-Association/IDS-testbed#100]
Hello team,

I have been trying to enable point to point communication between IDS-testbed connector B with external dataspace connector and ran across an error which looks like this in terminal:

![Capture](https://user-images.githubusercontent.com/110538109/198993711-1b388f18-93c3-4d6c-8f1c-e6553cb269fb.PNG)

Can I get some guidance on this?

**Comment by jfernandezsqs** [comment]
Hello @maliks3 ,
It seems that your signing key certificate is not appropriate.
I do not know what configuration or steps you have followed to generate the certificates and implement them in the DSCB and in your external component. If you tell me how you have generated those certificates maybe I see the problem and it can be solved.
Keep in mind the open issue #97 . There it is detailed the need of a CA that offers certificates including custom Subject Alternative Names and IP addresses.
