### ISSUE TITLE
please update old jiveon.com links 

### ISSUE THREAD

**Issue by robertgroh** [International-Data-Spaces-Association/IDS-testbed#108]
The file [CertificateAuthority/README.md](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/CertificateAuthority/README.md#link-to-the-current-specification) links to jiveon.com for the certificate policy,
but as the [industrialdataspace.jiveon.com](https://industrialdataspace.jiveon.com) is no longer available, this is a dead link.

Can someone replace the https://industrialdataspace.jiveon.com/docs/DOC-3611 link (maybe by uploading the referenced silde/file).

**Comment by jfernandezsqs** [comment]
Hello @robertgroh,
This issue has been notified in issue #105 
I will assign to this issue a person that could fix it

**Comment by robertgroh** [comment]
Sorry,  I didn't search for the other issue.
Lets close this as a duplicate of #105
