### ISSUE TITLE
Improve rendering on GitBook

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/IDS-testbed#116]
The IDS Reference testbed is rendered via Gitbook to https://docs.internationaldataspaces.org/ids-reference-testbed/

The configuration should be updated to:

- [ ] use the right Start Page (README.md)
- [ ] Update the TOC and navigation bar

**Comment by jfernandezsqs** [comment]
Thanks for the update and the proposed improvement in the IDS-testbed.
I have reviewed the proposed changes and I think it should be included at the `SUMMARY.md` file the `Testsuite` folder.
