### ISSUE TITLE
Problems adding new connector to ecosystem

### ISSUE THREAD

**Issue by Urtza2** [International-Data-Spaces-Association/IDS-testbed#118]
I have made the folling steps:
1.-python3 pki.py cert create --subCA ReferenceTestbedSubCA --common-name connectorc --algo rsa --bits 2048 --hash sha256 --country-name ES --organization-name ORG--unit-name TestHPA --server --client --san-name connectorc --san-name localhost --san-ip 127.0.0.1
2.-openssl pkcs12 -export -out connectorC.p12 -inkey connectorc.key -in connectorc.crt -passout pass:password
3.-openssl pkcs12 -in connectorC.p12 -out connectorC.cert -nokeys -nodes -passin pass:password
4.-Copy "connectorC.cert" to DAPS/keys directory
5.- Register connector in DAPS: ./register_connector.sh connectorC
6.- Modify docker-compose.yml to include new connector and modify config.json file.
7.- Add new DNS to etc/hosts

Wwhen I try to consume (connectorC) provider (connectorA) artifacts I have the following error:
**connectorc       | 2023-02-23T10:33:44,166 [https-jsse-nio-8085-exec-5] ERROR - PRODUCTIVE_DEPLOYMENT: No IDS-Message sent! No DAT could be acquired from DAPS! [code=(IMSCOE0001), reason=(Error connecting to DAPS (possibly currently not reachable or wrong DAPS-URL): Unexpected code Response{protocol=http/1.1, code=400, message=Bad Request, url=https://omejdn/auth/token} Body: {"error":"invalid_client","error_description":"Client unknown"})]

connectorc       | 2023-02-23T10:33:44,171 [https-jsse-nio-8085-exec-5] WARN - Connection to DAPS could not be established. [exception=(Error connecting to DAPS (possibly currently not reachable or wrong DAPS-URL): Unexpected code Response{protocol=http/1.1, code=400, message=Bad Request, url=https://omejdn/auth/token} Body: {"error":"invalid_client","error_description":"Client unknown"})]

connectorc       | 2023-02-23T10:33:44,204 [https-jsse-nio-8085-exec-5] WARN - Unable to retrieve valid DAT. [exception=(Access is denied)]**

**Comment by Urtza2** [comment]
I forgot this step...
8.- keytool -import -alias connectorC -file connectorc.crt -storetype PKCS12 -keystore truststore.p12

**Comment by Urtza2** [comment]
When tutorial says:
Add the certificate provided by the local CA, newly created by the local CA or provided by Fraunhofer AISEC. Place the certificate at the folder `DAPS/keys/omejdn/` with name `omejdn.key` to avoid dependency issues later on.

I have to delete omejdn.key file in 'DAPS/keys/omejdn' directory and what file I have to put there with "omejdn.key", the new "connectorC.key" file?

**Comment by jfernandezsqs** [comment]
Hello @Urtza2,
I have followed your steps and I get no error.
Could you please share here the docker-compose.yml and config.json file of (point 6) you have used?

7.- Add new DNS to etc/hosts -> You do not need to fo this point because it is already done with the previous points and point 8.

**Comment by jfernandezsqs** [comment]
> When tutorial says: Add the certificate provided by the local CA, newly created by the local CA or provided by Fraunhofer AISEC. Place the certificate at the folder `DAPS/keys/omejdn/` with name `omejdn.key` to avoid dependency issues later on.
> 
> I have to delete omejdn.key file in 'DAPS/keys/omejdn' directory and what file I have to put there with "omejdn.key", the new "connectorC.key" file?

This part of the documentation details the process to change the signing key of the DAPS component. 
You only have to change the Dataspace Connector to add a new connector to the IDS-testbed and perform the changes related in the documentation:
- Add the certificate to the DAPS's client list,
- Configure your connector (truststore, config.json, create proper certificate and docker-compose.yml)).

**Comment by Urtza2** [comment]
[
[config.txt](https://github.com/International-Data-Spaces-Association/IDS-testbed/files/10825562/config.txt)
[docker-compose.txt](https://github.com/International-Data-Spaces-Association/IDS-testbed/files/10825565/docker-compose.txt)
](url)

**Comment by Urtza2** [comment]
I have to change the extension of these file in order to attach them, sorry.

**Comment by Urtza2** [comment]
I am not sure what I am doing wrong I am able last week to add two new connectors but now during last three days I have receiveing this error.

**Comment by jfernandezsqs** [comment]
The config.json and docker-compose,.yml files seem to be fine.
Just to make sure, could you check at the route `DAPS/config/clients.yml` the content of your certificate? 
Does it contain the attribute `keyid` dividing the SKI AKI at the `client-id` line content?

**Comment by Urtza2** [comment]
It has the following:
- client_id: 44:55:31:10:C0:D4:66:85:55:1E:C1:18:26:CE:53:C5:D7:86:EA:34:41:30:3C:7E:87:C2:EF:66:72:27:91:82:EF:56:E9:0C:5C:2B:BC:2B
  client_name: connectorC
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://connectorC.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: f954d363bc1ab323299298de39fadda7ed7fbd1259450ff23abe3ce3c69c39fe

**Comment by jfernandezsqs** [comment]
Okay, I see the error.
Please change this line `client_id` with the following content and try it again.
```
client_id: 44:55:31:10:C0:D4:66:85:55:1E:C1:18:26:CE:53:C5:D7:86:EA:34:keyid:41:30:3C:7E:87:C2:EF:66:72:27:91:82:EF:56:E9:0C:5C:2B:BC:2B
```

Which version of Ubuntu are you using?
Which set-up are you using (OS _Ubuntu_XXX_)?

**Comment by Urtza2** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
I have change this line that now I am deploying it again

**Comment by Urtza2** [comment]
I have the following again:
connectorc             | 2023-02-24T15:29:53,877 [https-jsse-nio-8082-exec-5] ERROR - PRODUCTIVE_DEPLOYMENT: No IDS-Message sent! No DAT could be acquired from DAPS! [code=(IMSCOE0001), reason=(Error connecting to DAPS (possibly currently not reachable or wrong DAPS-URL): Unexpected code Response{protocol=http/1.1, code=400, message=Bad Request, url=https://omejdn/auth/token} Body: {"error":"invalid_client","error_description":"Error decoding JWT: No verification key available"})]
connectorc             | 2023-02-24T15:29:53,879 [https-jsse-nio-8082-exec-5] WARN - Connection to DAPS could not be established. [exception=(Error connecting to DAPS (possibly currently not reachable or wrong DAPS-URL): Unexpected code Response{protocol=http/1.1, code=400, message=Bad Request, url=https://omejdn/auth/token} Body: {"error":"invalid_client","error_description":"Error decoding JWT: No verification key available"})]
connectorc             | 2023-02-24T15:29:53,902 [https-jsse-nio-8082-exec-5] WARN - Unable to retrieve valid DAT. [exception=(Access is denied)]

**Comment by jfernandezsqs** [comment]
Please execute this section of the [guide](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/InstallationGuide.md#stop-and-delete-testbed-set-up) and try again.

**Comment by jfernandezsqs** [comment]
> Distributor ID: Ubuntu Description: Ubuntu 22.04.1 LTS Release: 22.04 I have change this line that now I am deploying it again

Okay, you are using release 22.04
I will test it with that version.

**Comment by Urtza2** [comment]
Are you from SQS Spain company isn't it? I work in Tecnalia, if you want we can write messages in Spanish ;-)

**Comment by Urtza2** [comment]
register_connector.sh  script it puts:  CLIENT_ID="$SKI:$AKI"
It doesn't put "keyid" between SKI and aKI.
"register_connector.sh" :
#!/bin/sh

if [ ! $# -ge 1 ] || [ ! $# -le 3 ]; then
    echo "Usage: $0 NAME (SECURITY_PROFILE) (CERTFILE)"
    exit 1
fi

CLIENT_NAME=$1

CLIENT_SECURITY_PROFILE=$2
[ -z "$CLIENT_SECURITY_PROFILE" ] && CLIENT_SECURITY_PROFILE="idsc:BASE_SECURITY_PROFILE"

CLIENT_CERT="keys/$CLIENT_NAME.cert"

SKI="$(openssl x509 -in "keys/${CLIENT_NAME}.cert" -noout -text | grep -A1 "Subject Key Identifier" | tail -n 1 | tr -d ' ')"
AKI="$(openssl x509 -in "keys/${CLIENT_NAME}.cert" -noout -text | grep -A1 "Authority Key Identifier" | tail -n 1 | tr -d ' ')"
CLIENT_ID="$SKI:$AKI"

CLIENT_CERT_SHA="$(openssl x509 -in "$CLIENT_CERT" -noout -sha256 -fingerprint | tr '[:upper:]' '[:lower:]' | tr -d : | sed 's/.*=//')"
echo $CLIENT_ID
cat >> config/clients.yml <<EOF
- client_id: $CLIENT_ID
  client_name: $CLIENT_NAME
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: $CLIENT_SECURITY_PROFILE
  - key: referringConnector
    value: http://${CLIENT_NAME}.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: $CLIENT_CERT_SHA
  import_certfile: $CLIENT_CERT
EOF

**Comment by Urtza2** [comment]
I think that the problem is that register_connector.sh in CLIENT_ID variable doesn't put "keyid" string. I don't know what it is happening, I'll try to change the register_connector.sh in order to concat "keyid" string between SKI and AKI.
I'll try to start again with another connector, connectorC  works putting "keyid" manually into CLIENT_ID value as you told me before.

**Comment by Urtza2** [comment]
I have updated "register_connector.sh" script to include "keyid" between SKI and AKI
I have changed:
CLIENT_ID="$SKI:$AKI"
By..

CLIENT_ID="$SKI:keyid:$AKI"

Maybe it is a bug into script?

I have a question regarding this:
keytool -import -alias connectorC -file connectorc.crt -storetype PKCS12 -keystore truststore.p12

For each new connector it is neccesary to import its certificate into truststore.p12?


I have observed into IDS-TESTbed that if you want to establish communication between two connectors (A and B for example) both of them should be into truststore.p12 otherwise gets PKIX error. Isn't it?

Thanks a lot for everything

**Comment by Urtza2** [comment]
Good morning,
Maybe it is an issue of OpenSSL version that I have installed. In my version AKI doesn't have "keyid" and that's why I have problems with CLIENT_ID.
Which version of OPENSSL do you have or do you think that it is mandatory?
Thanks

**Comment by jfernandezsqs** [comment]
> I have a question regarding this: keytool -import -alias connectorC -file connectorc.crt -storetype PKCS12 -keystore truststore.p12
> 
> For each new connector it is neccesary to import its certificate into truststore.p12?
> 
> I have observed into IDS-TESTbed that if you want to establish communication between two connectors (A and B for example) both of them should be into truststore.p12 otherwise gets PKIX error. Isn't it?


Yes, for now as it is a non production environment it is required to add each certificate into the `truststore.p12`. 
In production scenarios it is supposed that just having the different CA and SubCAs at the `truststore. p12` will ensure that the device certificates will be trusted because the root is trusted.

**Comment by Urtza2** [comment]
Thanks for your help!!
We can close the issue, can't we?

**Comment by jfernandezsqs** [comment]
> Thanks for your help!! We can close the issue, can't we?

Yes, thanks
