### ISSUE TITLE
Official specification CA

### ISSUE THREAD

**Issue by jfernandezsqs** [International-Data-Spaces-Association/IDS-testbed#12]
I am not able to find the documentation specification for the CA.
In the link to the current specification provided (https://industrialdataspace.jiveon.com/docs/DOC-3611) it appears the following information:
![image](https://user-images.githubusercontent.com/82888094/132351903-dcc1d584-6838-4bc2-9f56-e91bfac8d305.png)
Where can I find the detailed specification?

**Comment by jfernandezsqs** [comment]
Following the documented technical requirements I have encountered the following discrepancies:

Root CA
                              Key type: Secp521r1
                              Key length: 521 bits
                              Signature: SHA512
                              Duration: 10y
Sub CA
                              Key type: Secp384r1
                              Key length: 384 bits
                              Signature: **SHA512**
                              Duration: 5y
Device Cert
Key type: Secp256r1
                              Key length: 256 bits
                              Signature: **SHA384**
                              Duration: 3y
 
There is a small contradiction between slides 8 and 9 regarding the Sub CA and Dev Certs:
Slide 8 shows
```
1.      Sub CA
SHA512 and SECP384r1
2.      Dev Certs
SHA384 and SECP256r1
```
Slide 9 shows
```
Actual algorithms are chosen based on length of the key being used
1.      Sha512ecdsa, when a Root CA key of 512/521 Bit is being used
2.      Sha384ecdsa, when a Sub CA key of 384 Bit is being used
3.      Sha256ecdsa, when a EE key of 256 Bit is being used

Making
3.      Sub CA
SHA384 and SECP384r1
5.      Dev Certs
SHA256 and SECP256r1
```

**Comment by Sonia-IDSA** [comment]
Waiting for Atos CA
