### ISSUE TITLE
Provider credentials - how to set them

### ISSUE THREAD

**Issue by IgorBalog-Eng** [International-Data-Spaces-Association/IDS-testbed#121]
If provider connector requires Authorization header to be present, how can we pass that value?
If we set Authorization header - that value will be used to authorize DSC consumer connector.

How can we set value, Authorization or username and password, required for provider connector.

For example, our connector (TRUEConnector) requires Authorization header to be present and when we try to test our connector in Testbed environment, we get rejection message back in DSC consumer, and in TC logs, we have log line, saying Authorization header not present!!!, and indeed, with debugging, header is not present.

This might be also a issue for Clearing House (and Broker?) integration, since Fraunhofer CH (the one we used locally to verify integrability) requires also Authorization header when making request.

**Comment by jfernandezsqs** [comment]
Hello @IgorBalog-Eng,

In your deployment scenario, do you have your TRUEConnector deployed in the same network as the rest of components of the IDS-testbed? If not, you can try to deploy it in the same network.

Which tool are you using to perform the calls from TRUEConnector to the DSC-consumer IDS-testbed connector?
For example, using Postman in can be detailed the Authorization Credentials at the secftion `Authorization --> Type --> Basic Auth` detailing there the Username and Password for the request.

**Comment by IgorBalog-Eng** [comment]
Hello Josu
We have both systems connected and they are in the same network - testbed one.
To prove this, our connector can fetch token from Omejdn daps from Testbed "docker compose" and Testbed network.

We are using postman to send requests, and we are setting Basic authorization in request, but this authorization is needed to "open the door" of the DSC consumer connector, and we need another key, that will "open the door" of the TrueConnector Provider. And we do not know how to set this second authorization in request for consumer DSC.

**Comment by IgorBalog-Eng** [comment]
Hello @SebastianOpriel and @willemdatema 
@jfernandezsqs pointed you as right contact person for the issue we have experienced. Sebastian was/still is maintainer of Dataspace connector and Willem was pointed as person from TNO that has managed to interoperate their connector with the IDS-testbed .

Can you provide any feedback on how to solve issue we have with passing 2 Authorization headers when DSC is acting as consumer? First authorization header, from postman, is needed for DSC, second for provider TRUEConnector.
Is there some way to set in body of the request some additional parameters, that will be used by DSC to create authorization header when making call towards provider?
Thanks

**Comment by SebastianOpriel** [comment]
Do I understand it correctly, that you need Authorization on IDS Endpoint of TRUEConnector? That's not possible, as the IDS protocol does not foresee this. 

Authentication headers are at DSC just present for
- access Connector API (Basic auth)
- access data sources / sinks

**Comment by IgorBalog-Eng** [comment]
Not an issue since specification does not foresee that data endpoint of the connector has credentials.
