### ISSUE TITLE
Error while registering broker with connector

### ISSUE THREAD

**Issue by raj-ritu17** [International-Data-Spaces-Association/IDS-testbed#130]
I was trying to setup the testbed and followed the example guides.

at the following steps I am getting the error while trying to register the broker at the connector.
as per example are given here: https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/PreparingPreconfiguredSetup.md#guide-for-preparing-and-validating-the-preconfigured-setup
```
Register Connector A at MetaData Broker: POST /api/ids/connector/update
At the Swagger UI of Connector A insert the following recipient url for message POST /api/ids/connector/update:

https://broker-reverseproxy/infrastructure
```

I am receiving `message: "Unable to retrieve valid DAT".  `

I have followed the following guideline also, but doesn't help:  https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/v6/IdsEcosystem/Broker

---------------
Please, can you provide a guide or a simple example where we can successfully create the following scenarios:
create a resource, offer, rules, catalogues, contracts,  policies  and both connector can consume or receive data including registering metadata broker. 

It would be very helpful if we can have a simple producer-consumer working example at one place with basic connector example which can demonstrate the dataspace capabilities (basic functionalities such as creating offer, rules, policy, resource, registering, negotiating  and consuming). Too many documents complicate the process and confuse the users which one they should follow as a starting point.

Thank you for the help in advance!

**Comment by jfernandezsqs** [comment]
Hello @raj-ritu17,

Please follow the IDSA Reference Testbed Installation guide detailed [here](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/InstallationGuide.md). 
There it is detailed the hardware requirements and in a few commands how to deploy the [preconfigured testbed](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/InstallationGuide.md#target-view-preconfigured-testbed).

When you have the testbed deployed please use the [postman collection](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/TestbedPreconfiguration.postman_collection.json), there it is detailed a simple example which you just need to execute with Postman tool (DSC provider offers data, DSC’s are registered at the MDB and it is performed a contract negotiation).

**Comment by jfernandezsqs** [comment]
Hi @raj-ritu17,
I hope that the proposed solution has helped you and that your problem has been solved.
Therefore, as there has been no reply form your side, I am closing this issue. If for any reason you still have the error, do not hesitate to reopen this issue and provide more information on the error.
