### ISSUE TITLE
 IDS-testbed target view:preconfigure config error

### ISSUE THREAD

**Issue by itachiliu** [International-Data-Spaces-Association/IDS-testbed#131]
I installed IDS-testbed on the basis of  [IDS-testbed/InstallationGuide.md at master · International-Data-Spaces-Association/IDS-testbed (github.com)](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/InstallationGuide.md#target-view-preconfigured-testbed)  The target view: preconfigure testbed is adopted when I install. But there are some errors in the installation.

After

`docker-compose up`
 
I can't access 

 [https://localhost:443](https://localhost/)

 https://localhost:444/

 https://localhost:8080/

 https://localhost:8081/

Screenshots are as follows:
![image](https://github.com/International-Data-Spaces-Association/IDS-testbed/assets/22728196/9bd9e428-576e-4050-bfca-107b0cb0d74c)

![image](https://github.com/International-Data-Spaces-Association/IDS-testbed/assets/22728196/75507037-aeaf-4dbb-8681-d4d1010f4271)

![image](https://github.com/International-Data-Spaces-Association/IDS-testbed/assets/22728196/ee1d0d44-7960-4d8a-8442-6d4164d1da93)

![image](https://github.com/International-Data-Spaces-Association/IDS-testbed/assets/22728196/700c166e-e9ab-4785-a36b-1681a3a9eaf5)

I'm sure I started the docker successfully. Is there anything wrong with Certification Authenticity?

Note:

The docker-compose.yml has a bug when I install the testbed in my environment.

If the Postgres image version is 13, the testbed can't start successfully, so I modified the version to 12 and it worked.

I don't know if this error only happens in my environment or any environment, so I am giving you this information back.
![image](https://github.com/International-Data-Spaces-Association/IDS-testbed/assets/22728196/52ea59da-42af-49e7-8c33-99e72057a486)

**Comment by jfernandezsqs** [comment]
Hello @itachiliu,

The certificates used for the IDS-testbed are self-signed and the navigators do not have them as trusted certificates.
I propose two ways in which these access issue could be solved.
1) Include localhost and 127.0.0.1 at your hosts (follow this [guide](https://linuxize.com/post/how-to-edit-your-hosts-file/#:~:text=The%20instructions%20below%20are%20valid%20for%20all%20Linux,and%20add%20your%20new%20entries%3A%20Save%20the%20changes.)) and then try with your browser to access the endpoints of the components.
2) Use chromium-browser to access the component endpoints.
In a terminal execute:
```
sudo apt install chromium-browser
```
Access that browser and then the access issue should be solved.

Regarding the Postgres image version 13 issue at your environment. I am not having that problem in my environment. 
Could you please provide which environment you are using?

**Comment by itachiliu** [comment]
Dear jfernandezsqs,

Thanks for your reply and I will try your suggestion. 

Here is my environment information:

`#86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

I hope this will help you.

**Comment by jfernandezsqs** [comment]
I understand that the proposed solution has solved the problem. Therefore, I close this issue.
In case you continue to have problems, do not hesitate to reopen this issue.
