### ISSUE TITLE
An error occurred while registering connector with the broker using the host ip address

### ISSUE THREAD

**Issue by fcm2000105** [International-Data-Spaces-Association/IDS-testbed#133]
The broker runs on a host with IP address 100.75.144.100, I want to register the connector in https://100.75.144.100:444/infrastructure rather than https://broker-reverseproxy. I modified the testbed3.crt certificate to make host 100.75.144.100 a valid DNS and I encountered the following error:
connectorb           | 2023-10-30T11:05:09,326 [http-nio-8081-exec-8] INFO - Cached DAPS DAT expired or no expiration set. [expiration=(2023-10-30T10:55:03.000+0000), code=(IMSCOI0052)]
omejdn-server        | 172.22.0.4 - - [30/Oct/2023:11:05:09 +0000] "POST /token HTTP/1.1" 200 1591 0.0352
omejdn               | 172.22.0.1 - - [30/Oct/2023:11:05:09 +0000] "POST /auth/token HTTP/1.1" 200 1591 "-" "okhttp/4.10.0" "-"
connectorb           | 2023-10-30T11:05:09,440 [http-nio-8081-exec-8] INFO - Successfully received DAT from DAPS. [code=(IMSCOI0054)]
connectorb           | 2023-10-30T11:05:09,546 [http-nio-8081-exec-8] INFO - Successfully loaded Keystore. [code=(IMSCOI0049)]
connectorb           | 2023-10-30T11:05:09,608 [http-nio-8081-exec-8] INFO - Successfully loaded Truststore. [code=(IMSCOI0049)]
connectorb           | 2023-10-30T11:05:09,615 [http-nio-8081-exec-8] INFO - Using cached DAPS DAT. [expiration=(2023-10-30T12:05:09.000+0000), code=(IMSCOI0053)]
connectorb           | 2023-10-30T11:05:09,637 [http-nio-8081-exec-8] INFO - Sending request to https://100.75.144.100:444/infrastructure ... [code=(IMSMEI0065)]
omejdn-server        | 172.22.0.4 - - [30/Oct/2023:11:05:10 +0000] "POST /token HTTP/1.1" 400 63 0.0024
omejdn               | 172.22.0.1 - - [30/Oct/2023:11:05:10 +0000] "POST /auth/token HTTP/1.1" 400 63 "-" "okhttp/3.12.1" "-"
broker-core          | de.fraunhofer.iais.eis.ids.component.core.TokenRetrievalException: Unable to retrieve DAPS token.
broker-core          | 	at de.fraunhofer.iais.eis.ids.component.ecosystemintegration.daps.DapsSecurityTokenProvider.getSecurityToken(DapsSecurityTokenProvider.java:96)
broker-core          | 	at de.fraunhofer.iais.eis.ids.component.core.SecurityTokenProvider.getSecurityTokenAsDAT(SecurityTokenProvider.java:12)
broker-core          | 	at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.handle(MessageDispatcher.java:69)
broker-core          | 	at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.lambda$dispatch$2(MessageDispatcher.java:51)
broker-core          | 	at java.base/java.util.Optional.map(Optional.java:265)
broker-core          | 	at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.dispatch(MessageDispatcher.java:51)
broker-core          | 	at de.fraunhofer.iais.eis.ids.component.core.DefaultComponent.process(DefaultComponent.java:45)
broker-core          | 	at de.fraunhofer.iais.eis.ids.component.interaction.multipart.MultipartComponentInteractor.process(MultipartComponentInteractor.java:87)
broker-core          | 	at de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.processMessage(ComponentController.java:237)
broker-core          | 	at de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.infrastructureLevelCommunication(ComponentController.java:205)
broker-core          | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
broker-core          | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
broker-core          | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
broker-core          | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
broker-core          | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
broker-core          | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
broker-core          | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
broker-core          | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
broker-core          | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
broker-core          | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
broker-core          | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
broker-core          | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
broker-core          | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
broker-core          | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
broker-core          | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
broker-core          | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
broker-core          | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
broker-core          | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
broker-core          | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core          | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
broker-core          | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core          | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core          | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
broker-core          | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
broker-core          | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core          | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core          | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
broker-core          | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
broker-core          | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core          | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core          | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
broker-core          | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
broker-core          | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core          | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core          | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
broker-core          | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
broker-core          | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core          | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core          | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
broker-core          | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
broker-core          | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
broker-core          | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
broker-core          | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
broker-core          | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
broker-core          | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
broker-core          | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
broker-core          | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
broker-core          | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
broker-core          | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
broker-core          | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
broker-core          | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
broker-core          | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
broker-core          | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
broker-core          | 	at java.base/java.lang.Thread.run(Thread.java:829)
broker-core          | Caused by: java.io.IOException: Unable to retrieve DAPS token (response code: 400) 
broker-core          |  Response: {"error":"invalid_client","error_description":"Client unknown"}
broker-core          | 	at de.fraunhofer.iais.eis.ids.component.ecosystemintegration.daps.DapsTokenRetriever.acquireAccessTokenFromDaps(DapsTokenRetriever.java:190)
broker-core          | 	at de.fraunhofer.iais.eis.ids.component.ecosystemintegration.daps.DapsTokenRetriever.retrieveToken(DapsTokenRetriever.java:101)
broker-core          | 	at de.fraunhofer.iais.eis.ids.component.ecosystemintegration.daps.DapsSecurityTokenProvider.getSecurityToken(DapsSecurityTokenProvider.java:94)
broker-core          | 	... 63 more
broker-reverseproxy  | 172.22.0.1 - - [30/Oct/2023:11:05:11 +0000] "POST /infrastructure HTTP/1.1" 200 1503 "-" "okhttp/4.10.0"
connectorb           | 2023-10-30T11:05:11,132 [http-nio-8081-exec-8] INFO - Successfully received response to request. [code=(IMSMEI0067)]
connectorb           | 2023-10-30T11:05:11,164 [http-nio-8081-exec-8] INFO - Successfully passed SHACL-Validation. [code=(IMSMEI0064)]
connectorb           | 2023-10-30T11:05:11,237 [http-nio-8081-exec-8] DEBUG - Received unexpected response message. [response=({reason=https://w3id.org/idsa/code/INTERNAL_RECIPIENT_ERROR, payload=Failed to retrieve own DAPS token, preventing a valid response., type=class de.fraunhofer.iais.eis.RejectionMessageImpl})]

**Comment by jfernandezsqs** [comment]
Hello @fcm2000105,
Please take a look at issue #132 regarding MDB configuration. 
I do not know which is your deployment but it seems that the MDB is not able to communicate properly with the DAPS.
Maybe it is required on your side to generate MDB image with your used MDB certificate and reachable DAPS IP.

**Comment by fcm2000105** [comment]
OK, I will try that. Thank you very much!
