### ISSUE TITLE
Looking for a contact

### ISSUE THREAD

**Issue by emilienIMT** [International-Data-Spaces-Association/IDS-testbed#135]
Hello 
I would like to know if someone is still receiving/dealing the issues of this repository please

**Comment by jfernandezsqs** [comment]
Hello @emilienIMT,
I will move the issue encountered on #134 in order to solve it ASAP.

**Comment by jfernandezsqs** [comment]
For any future doubt or problem with the IDS-testbed please assign @jfernandezsqs as assignee to the issue.
I close this issue.
