### ISSUE TITLE
Interacting with the Broker: Performing SPARQL queries through the Connector

### ISSUE THREAD

**Issue by tharindupr** [International-Data-Spaces-Association/IDS-testbed#137]
Examples for querying the Meta Data Broker will help us understand the end-to-end customer journey of an IDSA consumer. This can probably be added to the Postman collection. In addition, how to directly interact with the Meta Data Broker (without forwarding through a Connector) will also be helpful.

**Comment by jfernandezsqs** [comment]
Hello @tharindupr!
The objective of the IDS-testbed is not focused on the detailed end-to-end functionalities of the Metadata Broker, this is dependent on the Metadata Broker documentation.
I can provide you with the following MDB links that may help you:
- [Interacting with the IDS Metadata Broker]( https://github.com/International-Data-Spaces-Association/metadata-broker-open-core?tab=readme-ov-file#43-interacting-with-the-ids-metadata-broker)
- [Broker API in SwaggerHub](https://app.swaggerhub.com/apis/idsa/IDS-Broker/)

**Comment by jfernandezsqs** [comment]
I hope the feedback has been helpful. 
I close the issue, in case of any additional doubts do not hesitate to reopen the issue.
