### ISSUE TITLE
Which version of dataspaces protocol is this testing?

### ISSUE THREAD

**Issue by Excds** [International-Data-Spaces-Association/IDS-testbed#138]
This is more of a question than a bug report. It is really not clear to me which version of the dataspaces protocol this is testing. Is it version 0.8 or has this been updated to the 2024.1 version?

**Comment by mspiekermann** [comment]
This is not yet using any version of the DSP. Discussion on updating the certification process with DSP as its basis is currently discussed in the corresponding working group of IDSA. You are not the only one waiting for this :) Meanwhile you can have a look into DSP's accompanying Technical Compatibility Kit [TCK](https://github.com/eclipse-dataspacetck/cvf)

**Comment by jfernandezsqs** [comment]
For the moment, I close this issue as it does not affect the actual status of IDS-testbed. 
The scope is to try to implement the DSP in the IDS-testbed.
