### ISSUE TITLE
IDS-Testbed - Problem Request artifact and Offers

### ISSUE THREAD

**Issue by chrkli7** [International-Data-Spaces-Association/IDS-testbed#142]
we got the IDS TESTBED running and ran the preconfiguration in postman:

 
![grafik](https://github.com/International-Data-Spaces-Association/IDS-testbed/assets/126881286/aa3a30a2-9c7d-4757-99ee-26898e57739e)

so far so good ... Unfortunately, we get an error message when creating an offer according to your instructions:

https://docs.internationaldataspaces.org/ids-knowledgebase/v/ids-reference-testbed/getting-started-with-ids-reference-testbed/preparingpreconfiguredsetup

 
![grafik](https://github.com/International-Data-Spaces-Association/IDS-testbed/assets/126881286/0b2d1f47-11c6-4fc1-9e47-9a0d370889a2)

In validating preconfigured Seutp: Interaction between connectors …the following error appears:
![grafik](https://github.com/International-Data-Spaces-Association/IDS-testbed/assets/126881286/283a2155-f8f5-4378-9d02-6e3cc9b601e4)

 How to solve this problem?

**Comment by jfernandezsqs** [comment]
This error should be fixed with pull request #143.
Please check again your error and the comment regarding the contract date.
I close this issue, if you continue to have problems feel free to open it again.
