### ISSUE TITLE
Request for Diverse JSON Schema Data to Develop AI Tool For Ingesting Data in IDS ecosystem

### ISSUE THREAD

**Issue by parwinderau** [International-Data-Spaces-Association/IDS-testbed#144]
Dear Team,

I am a PhD student at Aarhus University and an active contributor in the Dataspace domain.
In my new experiments, I am working on a Data Ingestion tool that deals with data heterogeneity for Dataspace. Therefore, I am building a Machine learning model. For this model, I need diverse kinds of JSON schema or metadata. I plan to develop this tool and contribute it to the IDS repository. So that non-technical users can ingest data in IDS with ease.  I would like to ask is there any possibility to get JSON schemas dataset or dbdump (around 1000 different schema samples I need) from any Deployed IDS publicaly or privately or any guidance where I can get that if you point out something.

Many thanks
BR
Parwinder
Email: parwinder@btech.au.dk
PhD Student, Department of Business Development and Technology, 
Aarhus University, Herning, Denmark.

**Comment by jfernandezsqs** [comment]
Hello @parwinderau,

I will look into it and if I find a JSON schema dataset with a great amount of samples I will supply it to you.
For the moment, I close this issue as it does not affect the IDS-testbed. However, if in the near future you get the model you are researching, I encourage you to generate a pull request in this repository to share it in the IDS-testbed deployment.
