### ISSUE TITLE
Guide the user through the Repository

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/IDS-testbed#18]
There are a lot of important information in the repo now. That is great. Now we have to improve the readability.  

- Is every document linked in the text
- Is the user guided through the relevant steps
- is every resource explained properly

We should reference [this](../Testbed/Example_ReferenceTestBed_UserGuide.md) from the README.md to guide the user through the Repository.

_Originally posted by @ssteinbuss in https://github.com/International-Data-Spaces-Association/IDS-testbed/pull/16#discussion_r772939661_

We should reference [this](../Testbed/Preparing_preconfigured_setup.md) from the README.md to guide the user through the Repository.

_Originally posted by @ssteinbuss in https://github.com/International-Data-Spaces-Association/IDS-testbed/pull/16#discussion_r772940106_

**Comment by aitorce** [comment]
The referenced pull request has been merged. Issue closed.
