### ISSUE TITLE
DSC Version unclear

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/IDS-testbed#19]
As already stated, it is unclear which DSC Version should be used.

- The [Testbed/readme.md](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/Testbed/README.md) refers to the DSC documentation so that you check out the **current main branch**
- The [Testbed/DataspaceConnector/readme.md](https://github.com/International-Data-Spaces-Association/IDS-testbed/tree/master/Testbed/DataspaceConnector) says **version 5.1.2** (inside the zip file is the main branch some commits after version 5.1.2)
- The linked [Test Suite ](https://gitlab.cc-asp.fraunhofer.de/ksa/ids-certification-testing) in the readme.md says you have to use **version 4.3.0**

So it would be nice to use a defined version for the whole testbed. For example the latest version.

**Comment by aitorce** [comment]
Thank you for your issue.

* In the pull request, I have updated the Testbed/Readme.md to refer to the DSC v6.2.0 documentation. 
* The new directory architecture has replaced this and it is no longer an issue. The repository will use v6.2.0
* I will bring this point internally.

**Comment by kretzschi** [comment]
Actually, we are not using the DSC in our test suite. The mentioned version 4.30 of the DSC in the README is optional and will be removed soon. Don't be confused with this point. We are using the DSC only to test our tests.

**Comment by Sonia-IDSA** [comment]
DSC in Test Suite Readme is optional. All other DSC version have been updated.
