### ISSUE TITLE
Error during the install.sh script

### ISSUE THREAD

**Issue by boxer-code** [International-Data-Spaces-Association/IDS-testbed#39]
Hi, I'm trying to execute the install.sh script but I'm struggeling with the error 
```
Unable to init server: Could not connect: Connection refused
# Failed to parse arguments: Cannot open display:
```
And none of the containers are running after the script. 
I'm pretty sure that the error is caused by the gnome-terminal command but I can't find a way to fix this. 
Am I missing something in the set up?

Thanks in advance!

**Comment by karikolehmainen** [comment]
Perhaps error is caused by running install script without GUI (X11 environment). Gnome-terminal commands launch docker (and docker-compose) for broker. Quick workaround for that is to remove gnome-terminal wrapper from docker calls and run docker and docker-compose in detached mode with -d switch.

**Comment by boxer-code** [comment]
Thanks that works for me!

**Comment by aitorce** [comment]
Gnome-terminal is no longer used in the install script. Please, refer to [PR 41](https://github.com/International-Data-Spaces-Association/IDS-testbed/pull/41)
