### ISSUE TITLE
gnome-terminal not working

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/IDS-testbed#43]
When the install script runs the following line:
```
gnome-terminal --title "CONNECTOR B" -e "docker run --publish 8081:8081 --name connectorb --network=broker-localhost_default dscb"
```
it opens a new terminal window that immediately closes. The container is not started up.
If I replace the -e option with -- , then the terminal stays open but shows the following error message:
```
Failed to execve: No such file or directory.
```
The workaround from #39 works. I would propose that the install.sh script should not open a new terminal window but use the -d option for starting the containers. This might fix #42 too.

**Comment by aitorce** [comment]
Thank you for your issue.

The initial idea was to let the users see how the components behave by looking at the terminal. I will look into removing the gnome-terminals and showing the users how to take a look look at the logs if they choose to.

**Comment by SebastianOpriel** [comment]
In my case I needed to use
`sudo apt install gnome-terminal`
instead of 
`sudo apt-get install gnome-terminal`

**Comment by aitorce** [comment]
The new install script has removed the use of `gnome-terminal` as is now launching the components in detatched mode. This should be fixed with [PR 41](https://github.com/International-Data-Spaces-Association/IDS-testbed/pull/41).
