### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/IDS-testbed#46]
Hi,
why did you copy the source code of the components (Connector, Broker, ...) into this repository? Why are you not using the DSC containers provided by the DSC developers in the Github repository (e.g. https://github.com/International-Data-Spaces-Association/DataspaceConnector/pkgs/container/dataspace-connector/15163462?tag=7.0.2)?
It would be much easier to adapt the testbed to newer versions of the components and files wouldn't need to be duplicated.

**Comment by jfernandezsqs** [comment]
PR #72  fix this issue.
