### ISSUE TITLE
Pitfalls during Testbed installation (CA creation)

### ISSUE THREAD

**Issue by kretzschi** [International-Data-Spaces-Association/IDS-testbed#47]
I came across some issues/inconsistencies with the Testbed installation guide and collected them.

- the mentioned directory in the [CA README](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/CertificateAuthority/README.md#installation) does not exist -> should be changed to
`cd CertificateAuthority`

- the [command to create a sub CA](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/CertificateAuthority/README.md#creation-of-a-sub-ca) is wrong. Correct is 
`python3 pki.py subca create --CA "Test CA" --common-name [Sub CA name]`

- before the 2nd step of the [device certificate creation](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/CertificateAuthority/README.md#creation-of-a-device-certificate) it should be mentioned, where the created key pair is located, namely in `CertificateAuthority/data/cert`.
Otherwise it is not clear where to find them.

- the last step of [fileing the certificates to the components](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/InstallationGuide.md#continue-here-after-the-official-documentation-has-been-followed) refers to a non existing folder `../../../DataspaceConnector/src/main/resources/conf`. I think it should refer to the two DataspaceConnectors within the testbed:
`cp {CERT_FILENAME}.p12 ../../../DataspaceConnectorA/src/main/resources/conf` and
`cp {CERT_FILENAME}.p12 ../../../DataspaceConnectorB/src/main/resources/conf`

Edit: Currently, I am not able to assign the issue so I use the mention functionality: @aitorce @jfernandezsqs

**Comment by aitorce** [comment]
Thank you for your issue. I will update the documentation with the changes mentioned above.

**Comment by jfernandezsqs** [comment]
The PR that fix this issue has been merged. Therefore, I close the issue.
