### ISSUE TITLE
Update dependencies in install-script

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/IDS-testbed#48]
It would be great to see an 
`sudo apt-get update`
at the beginning before the script installs any dependencies.

**Comment by aitorce** [comment]
This has been implemented in the `install.sh` script, [PR 41](https://github.com/International-Data-Spaces-Association/IDS-testbed/pull/41).

**Comment by jfernandezsqs** [comment]
The PR that fix this issue has been merged. Therefore, I close the issue.
