### ISSUE TITLE
Depenendency management

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/IDS-testbed#49]
It would be great to have a documentation from which repository and which commit / tag code is copied into the project. E.g. it is not clear which commit is used for the dataspaceconnector.
As suggested by @sebplorenz using official pre-build images would be great. If they were used (like in some scripts) a version shall be used instead of pulling the latest version, which can result in unforeseeable errors, not being able to rely on the current testbed configuration.

**Comment by Sonia-IDSA** [comment]
Updated for all components except Metadata Broker (WIP)
