### ISSUE TITLE
Simplify deployment for MVDS scenarios

### ISSUE THREAD

**Issue by CapacitorSet** [International-Data-Spaces-Association/IDS-testbed#55]
We at TOP-IX have been using the testbed as a Minimum Viable Data Space to evaluate the IDS architecture. Per our latest meeting with IDSA I'm writing down some constructive feedback from our experience.

To be clear, we appreciate the effort towards creating the testbed and the deployment went relatively well, and these are suggestions that can make it easier for other people to deploy an MVDS. I also understand that some of these points are effectively suggestions for specific projects (eg. the broker) and not for the testbed itself.

I think these steps could be effectively scripted or otherwise automated:
 - [creating certificates](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/InstallationGuide.md#continue-here-after-the-official-documentation-has-been-followed) and [adding DAPS keys and clients](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/InstallationGuide.md#adding-the-keys-to-the-daps) could be scripted;
 - [importing the DAPS certificates into the local keystore](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/InstallationGuide.md#open-the-conf-directory) could be scripted, but it would be interesting to further automate it using [Certificate Signing Requests](https://en.wikipedia.org/wiki/Certificate_signing_request) that could be issued by a script or init container and approved by the DAPS;
 - [configuring Omejdn](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/InstallationGuide.md#required-changes-in-the-configuration) could not require building a new docker image;
 - [configuring the broker](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/InstallationGuide.md#changes-in-the-docker-compose-file) could not require recompiling (if I recall correctly one can pass properties from the command line, but it is still required to recompile after altering the keystore).

Additionally, the testbed currently does not ship with a broker UI - that's fair since it is not required for operating the testbed, but one should keep it in mind when deploying a MVDS.

**Comment by jfernandezsqs** [comment]
Thanks for the feedback!
Some of the points detailed in this issue are taken into account in pull request `Switch to docker compose using testbed CA certificates # 71`
We will take into account the creation of certificates and their automatic implementation through a script in the components that are part of the IDS-testbed.

**Comment by Sonia-IDSA** [comment]
1. Creation of certificates included in issue #63 
2. Not solved, waiting for new CA. Issue #97
3. Solved
4. Issue with Metadata Broker described in issue #92
