### ISSUE TITLE
Fix Pull Requests Reviewers

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/IDS-testbed#56]
Hi,
can someone please fix the PR reviewers setting. There are PRs that already have been approved by two reviewers, but the PRs are not merged automatically. Maybe these reviewers need another role or something. E.g. https://github.com/International-Data-Spaces-Association/IDS-testbed/pull/41 has enough reviewers but is not merged.
@Sonia-IDSA can you do this?
Thanks.

**Comment by Sonia-IDSA** [comment]
Hi, 
I don´t think I can. I´d like to ask @ssteinbuss and @anilturkmayali for some support here. PR #54 is another example.
Thanks, 
Sonia

**Comment by Sonia-IDSA** [comment]
Hi again, 
We changed the permissions of the reviewers (@sebplorenz , @SebastianOpriel and @Arian-IDSA )
Issue can be closed
Sonia
