### ISSUE TITLE
Dockers are not compatible with Apple m1 chip

### ISSUE THREAD

**Issue by git-masoud** [International-Data-Spaces-Association/IDS-testbed#69]
connectors' dockers are not working in mac having m1 chip . Furthermore, metadata broker is running but unfortunately not functioning properly. This could be the case for windows or mac with other chips, therefore it would be nice to have Ubuntu as the compatible OS in the requirements.

**Comment by aitorcelaya** [comment]
Hello,

Ubuntu (currently 20.04.1 LTS) is defined as the OS of choice for the Testbed in here: https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/InstallationGuide.md#target-view-preconfigured-testbed.
