### ISSUE TITLE
docker-compose not successful in current version 

### ISSUE THREAD

**Issue by kretzschi** [International-Data-Spaces-Association/IDS-testbed#73]
Could not build the Testbed in current version with the docker-compose file.

Found some quick-fixes to make it run:

#### add version number to docker-compose.yaml
```
version: "3.0"
services:
  omejdn: ...
```

#### fix env variables by removing quotation marks
```
OMEJDN_VERSION=1.6.0
...
UI_VERSION=dev
```

**Comment by jfernandezsqs** [comment]
Hi @kretzschi!
Which version of docker-compose are you using?
Could you please paste the errors in this issue?
