### ISSUE TITLE
Docker has different behavior on Windows and Linux

### ISSUE THREAD

**Issue by alzcurda** [International-Data-Spaces-Association/IDS-testbed#79]
I cloned latest version of [test-bed ](https://github.com/International-Data-Spaces-Association/IDS-testbed/tree/Switch__Docker-compose) and I found that it works perfectly on Windows, but it doesn't work in Linux (Ubuntu 20.4). 

I used latest version of Docker-compose for both OS. 

I fixed it by:

- docker-compose.yml: adding the version. 

> version: '3.7'
> services:
>    omejdn:
>     image: nginx:1.21.6
>     container_name: omejdn
>     ports:
>       - 80:80

- .env: Removing ""

> ### The docker version to pull
> OMEJDN_VERSION=1.6.0
> 
> ### Your domain (e.g. sso.example.org)
> OMEJDN_DOMAIN=omejdn

I hope this can be useful for other people.

**Comment by jfernandezsqs** [comment]
Hello @alzcurda!
I am not facing that issue, however I have seen that you have used [Switch__Docker-compose](https://github.com/International-Data-Spaces-Association/IDS-testbed/tree/Switch__Docker-compose) branch.
Could you please try it again with the IDS-testbed [master](https://github.com/International-Data-Spaces-Association/IDS-testbed/tree/master) branch?

**Comment by alzcurda** [comment]
I used the master branch.
