### ISSUE TITLE
Developing IDS-testbed in a Kubernetes local cluster

### ISSUE THREAD

**Issue by CarlosCobAtos** [International-Data-Spaces-Association/IDS-testbed#82]
It has been added the necessary manifests to run IDS-testbed with K8s in a local environment. Also, Postman file has been modified to test the K8s environment connectivity, and finally, Kube-linter tests have been added to verify the code integrity.

**Comment by Sonia-IDSA** [comment]
Testbed deployment in Kubernetes not in scope for now.
