### ISSUE TITLE
PreparingPreconfiguredSetup issue

### ISSUE THREAD

**Issue by ValentinaIvanova** [International-Data-Spaces-Association/IDS-testbed#91]
Hello!

I have just deployed the test bed and now following the guide 
https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/PreparingPreconfiguredSetup.md#guide-for-preparing-and-validating-the-preconfigured-setup
So far I followed all steps for connector A and registering both connectors.

Now when I continue both these steps return the same json reply 
https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/PreparingPreconfiguredSetup.md#request-self-description-from-connector-a-post-apiidsdescription
https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/PreparingPreconfiguredSetup.md#request-information-regarding-the-desired-resource-post-apiidsdescription

I believe there is problem with the return value in the matter case or the endpoint is different.

I am using the following cURL commands to perform the first and the second request, respectively.
curl -vk  -u <user:pass> -X POST   https://localhost:8889/api/ids/description?recipient=https://connectora:8080/api/ids/data
 
 curl -vk  u <user:pass> -X POST   https://localhost:8889/api/ids/description?recipient=https://connectora:8080/api/ids/data&elementId=https://connectora:8080/api/catalogs/2ba4f400-06cb-4f6e-90c8-89491c626191

Thank you for your help in advance!
Valentina

**Comment by ValentinaIvanova** [comment]
Hello!

This is not an issue actually. By some reason the curl command was cutting the second parameter in the second cURL command. It works when the request URL and parameters are enclosed in quotes.

Best,
Valentina

**Comment by jfernandezsqs** [comment]
Hello, yes using quotes solves the curl command issue.

```
curl -vk u user:pass -X 'POST' 'https://localhost:8889/api/ids/description?recipient=https://connectora:8080/api/ids/data&elementId=https://connectora:8080/api/catalogs/2ba4f400-06cb-4f6e-90c8-89491c626191'
```
