### ISSUE TITLE
No such file 'extensions.sh' can be found in the 'keys' directory

### ISSUE THREAD

**Issue by johnnyxqliao** [International-Data-Spaces-Association/IDS-testbed#93]
According to the guideline, we can get the required aki/ski extensions by extensions.sh
Note: The user must extract the aki/ski extensions from the client's certificate to add the client to the Omejdn DAPS. If you are not certain on how to do this, the keys directory will have a script called extensions.sh. Once executed, input the certificate's filename and it will return the required aki/ski extensions.

But, no such file 'extensions.sh' can be found in the 'keys' directory.

**Comment by jfernandezsqs** [comment]
Hello @johnnyxqliao!
There will be a documentation update soon to solve it.
