### ISSUE TITLE
New CA needed for IDS-testbed

### ISSUE THREAD

**Issue by jfernandezsqs** [International-Data-Spaces-Association/IDS-testbed#97]
Waiting for ATOS CA implementation.

**Comment by jfernandezsqs** [comment]
The CA in the repo should provide an OCSP to enable revocation of issued certificates and checking the revocation status.

**Comment by Sonia-IDSA** [comment]
The certificates generated by the actual IDS-testbed CA do not have Subject Alternative Name to determine DNS and IP-address.

Currently, the DNS is handled by custom TLS certificates.

**Comment by mokamhuber** [comment]
We should take care that the CA tool fulfills at least the following requirements:
* capability to issue certificates using the cryptographic mechanisms and other cert features specified in the CA specification
* possibility to offer an OCSP server which issues OCSP responses on request
* Dependencies should be kept to a minimum - no disproportionate requirements concerning the environment or additional tooling necessary for executing the tools

**Comment by mokamhuber** [comment]
suggestions for tooling from the SubWG meeting:
* CFSSL: https://github.com/cloudflare/cfssl -> should be able to fulfill the requirements above, in the Repo https://github.com/Fraunhofer-AISEC/ids-pcp is an example how the IDS PKI could be configured/set up
* PKI-Engine: https://developer.hashicorp.com/vault/tutorials/secrets-management/pki-engine -> Carlos will ask his colleagues to support with the assessment of this tool

**Comment by jfernandezsqs** [comment]
SQS has performed a Demo of the Atos Web Portal CA during the Sub-working Group bi-weekly meeting.

**Comment by jfernandezsqs** [comment]
For version 1.2.0 of the IDS-testbed it has been included a Certificate Authority that uses CFSSL and provides a OCSP server for requesting the status of the generated certificates (e.g. revoked).
Documentation for this CA implementation is detailed [here](https://github.com/International-Data-Spaces-Association/IDS-testbed/tree/master/CertificateAuthority#certificate-authority-ca).
Therefore, I close this issue.
