### ISSUE TITLE
Testbed installation in a VM

### ISSUE THREAD

**Issue by Emilio-UAQ** [International-Data-Spaces-Association/IDS-testbed#99]
Dear all,

I'm currently trying to install the testbed on a Virtual Machine and I'm having issues getting the packages downloaded through the terminal, so I was wondering if it had to do anything with it being a Virtual Machine.

**Comment by jfernandezsqs** [comment]
Hello @Emilio-UAQ
Can you please attach your terminal logs to this opened issue?
In this way, we can help you with the problem you arefacing.

**Comment by jfernandezsqs** [comment]
Hello @Emilio-UAQ,
Are you still facing problems?
